### ISSUE TITLE
Maven artifact

### ISSUE THREAD

**Issue by RuedigerMoeller** [yuchi/java-npm-semver#1]
Hi,

congrats, after trying various java implementations of semver (and even considering to implement it myself) I found your work. Its the best and most solid implementation by a margin !

I'd like to include this as a dependency with one of my OS work (kontraktor-http). This includes a NPM clone written in java (i'm doing bundling + minification + react-jsx transpilation completely in java, so I don't want force users to install node just to be able to have a ´npm i install react react-dom´).

However LGPL disallows bundling inside a single artifact, so I'd need a artifact on maven.org. I could do this however it would be listed as "de.ruedigermoeller" ..

**Comment by yuchi** [comment]
You should find it already under

   group: "com.github.yuchi", name: "npm-semver"

Thanks for the compliments!

**Comment by RuedigerMoeller** [comment]
good :) maybe put that in README.MD

**Comment by yuchi** [comment]
Just did that (I don’t know how I missed that 😅 ).

**Comment by yuchi** [comment]
I also created a minimal usage guide on the README.

Please add issues if you find any or if you have any question.

**Comment by RuedigerMoeller** [comment]
kewl. for now it seems rather accurate. I can (auto-)install and run large frameworks + jsx apps without even having node/npm on my machine (e.g. material-ui, semantic-ui-react, react-bootstrap).
Fetching and resolving hundreds of node modules via "java-npm" (+your npm-semver) has not thrown any exception on various edge cases ('>14 <= 15') and the app showcases work correctly. Have not made an exact module@version comparision with an aequivalent npm install yet ..  however npm isn't deterministic anyway ;)

**Comment by yuchi** [comment]
Nice! Ham you give me some reference?

**Comment by RuedigerMoeller** [comment]
yup I can, however there is a LOT of other stuff included such as untertow, jsoup, .. which also are awesome libraries. Should add a 'references section' in general :)

A ready to run sample is here https://github.com/RuedigerMoeller/InstrinsicReactJSX
